/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import DTO.Bill;
import DTO.Service;
import DTO.Staff;
import DTO.Use_service;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duykh
 */
public class BillGUI extends javax.swing.JPanel {
    DefaultTableModel model;
    Staff staff = null;
    int index;
    /**
     * Creates new form StaffGUI
     */
    public BillGUI() {
        initComponents();
        showBill();
    }
    
    public void showBill() {
        ArrayList<Bill> list = Bill.SelectAll();
        model = (DefaultTableModel) tb_staff.getModel();
        int i=1;
        model.setColumnIdentifiers(new Object[]{
            "STT", "Họ tên khách hàng","Sđt","Cmnd", "Phòng thuê","Ngày thuê","Ngày trả phòng","Dịch vụ khách sử dụng (Ngày sử dụng)","Tổng tiền","Nhân viên đặt phòng","Nhân viên thanh toán"
        });
        model.setRowCount(0);
        for (Bill s : list) {
            Use_service use_service = Use_service.SelectbyIdCustomer(s.getBooking().getCustomer().getId());
            String services = "";
            if(use_service != null){
                for (int j = 0; j < use_service.getList_service().size(); j++) {
                    services += use_service.getList_service().get(j).getName()+" ("+use_service.getDate().get(j).toString()+") , ";
                }
            }
            model.addRow(new Object[]{
                i++, s.getBooking().getCustomer().getName(), s.getBooking().getCustomer().getSdt(),s.getBooking().getCustomer().getCmnd(),s.getBooking().getRoom().getName(),s.getBooking().getTimestamp().toString(),s.getTimestamp().toString(),services,s.getPrice()+".000đ",s.getBooking().getStaff().getName(),s.getStaff().getName()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Bill_output_btn = new javax.swing.JButton();
        Bill_output_btn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtext = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_staff = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1680, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Bill_output_btn.setBackground(new java.awt.Color(52, 152, 219));
        Bill_output_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_output_btn.setForeground(new java.awt.Color(255, 255, 255));
        Bill_output_btn.setText("Xuất hoá đơn");
        Bill_output_btn.setBorderPainted(false);
        Bill_output_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bill_output_btnMouseClicked(evt);
            }
        });
        Bill_output_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_output_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_output_btn);
        Bill_output_btn.setBounds(680, 90, 170, 50);

        Bill_output_btn1.setBackground(new java.awt.Color(52, 152, 219));
        Bill_output_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bill_output_btn1.setForeground(new java.awt.Color(255, 255, 255));
        Bill_output_btn1.setText("In hoá đơn");
        Bill_output_btn1.setBorderPainted(false);
        Bill_output_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bill_output_btn1MouseClicked(evt);
            }
        });
        Bill_output_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_output_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_output_btn1);
        Bill_output_btn1.setBounds(460, 90, 170, 50);

        jtext.setColumns(20);
        jtext.setRows(5);
        jScrollPane2.setViewportView(jtext);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(290, 30, 166, 0);

        tb_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ tên khách hàng", "Sđt", "Cmnd", "Phòng thuê", "Ngày thuê", "Ngày trả phòng", "Dịch vụ khách sử dụng (Ngày sử dụng)", "Tổng tiền", "Nhân viên đặt phòng", "Nhân viên thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_staff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tb_staff);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 38, 50));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin đặt phòng");
        jPanel2.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bill_output_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_output_btnActionPerformed
        // TODO add your handling code here:
        try{
            Workbook wb = new XSSFWorkbook();
            Sheet sheet = wb.createSheet("Bill");
            Row rowCol = sheet.createRow(0);
            for (int i = 0; i < tb_staff.getColumnCount(); i++) {
                Cell cell = rowCol.createCell(i);
                cell.setCellValue(tb_staff.getColumnName(i));
            }
            for (int j = 0; j < tb_staff.getRowCount(); j++) {
                Row row = sheet.createRow(j+1);
                for (int k = 0; k < tb_staff.getColumnCount(); k++) {
                    Cell cell = row.createCell(k);
                    if(tb_staff.getValueAt(j, k)!= null){
                        cell.setCellValue(tb_staff.getValueAt(j, k).toString());
                    }
                }
            }
            FileOutputStream out = new FileOutputStream(new File("Bill.xls"));
            wb.write(out);
            wb.close();
            out.close();
            JOptionPane.showMessageDialog(this, "Xuất file thành công");
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Bill_output_btnActionPerformed

    private void Bill_output_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bill_output_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_output_btnMouseClicked

    private void Bill_output_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bill_output_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_output_btn1MouseClicked

    private void Bill_output_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_output_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            int index = tb_staff.getSelectedRow();
            if(index == -1){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hoá đơn muốn in !");        
            }else{
                String a = "HOÁ ĐƠN THUÊ PHÒNG\n\nHọ tên khách hàng: "+tb_staff.getValueAt(index, 1)
                            +"\nSố điện thoại: "+tb_staff.getValueAt(index, 2)
                            +"\nChứng minh nhân dân: "+tb_staff.getValueAt(index, 3)
                            +"\nPhòng thuê: "+tb_staff.getValueAt(index, 4)
                            +"\nNgày thuê: "+tb_staff.getValueAt(index, 5)
                            +"\nNgày trả phòng: "+tb_staff.getValueAt(index, 6)
                            +"\nDịch vụ khách sử dụng (Ngày sử dụng): "+tb_staff.getValueAt(index, 7)
                            +"\nTổng tiền: "+tb_staff.getValueAt(index, 8)
                            +"\nNhân viên đặt phòng: "+tb_staff.getValueAt(index, 9)
                            +"\nNhân viên thanh toán: "+tb_staff.getValueAt(index, 10)
                            +"\n\nCảm ơn quý khách đã thuê phòng ở khách sạn chúng tôi";
                jtext.setText(a);
                boolean print = jtext.print();
                if(print){
                    JOptionPane.showMessageDialog(this, "In thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Bill_output_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bill_output_btn;
    private javax.swing.JButton Bill_output_btn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtext;
    private javax.swing.JTable tb_staff;
    // End of variables declaration//GEN-END:variables
}
