/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DTO.Booking;
import DTO.Customer;
import DTO.Service;
import DTO.Use_service;
import DTO.Staff;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.print.attribute.standard.PrinterMessageFromOperator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vanhi
 */
public class DeleteService extends javax.swing.JFrame {
    Use_serviceGUI ugui = new Use_serviceGUI();
    Use_service customer = new Use_service();
    /**
     * Creates new form EditRoom
     */
    public DeleteService(Use_service s) {
        initComponents();
        customer = s;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }
    
    public void infor(Use_serviceGUI BG){
        ugui = BG;
            title.setText("Xoá dịch vụ");
            txtName_customer.setText(customer.getCustomer().getName());
            txtName_customer.setEditable(false);
            txtName_room.setText(customer.getBooking().getRoom().getName());
            txtName_room.setEditable(false);
            for (int j = 0; j < customer.getList_service().size(); j++) {
                listService.addItem(customer.getList_service().get(j).getName()+"    "+customer.getList_service().get(j).getPrice()+".000đ"+"    "+customer.getDate().get(j).toString());
            }

//        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName_customer = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        txtName_room = new javax.swing.JTextField();
        listService = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(423, 464));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Xoá Dịch vụ");
        jPanel1.add(title);
        title.setBounds(40, 50, 340, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên khách hàng :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 200, 140, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phòng đặt :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 140, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dịch vụ :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 260, 140, 32);
        jPanel1.add(txtName_customer);
        txtName_customer.setBounds(170, 200, 210, 31);

        btnConfirm.setBackground(new java.awt.Color(52, 152, 219));
        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Xác nhận");
        btnConfirm.setBorderPainted(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm);
        btnConfirm.setBounds(40, 360, 340, 40);

        txtName_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName_roomActionPerformed(evt);
            }
        });
        jPanel1.add(txtName_room);
        txtName_room.setBounds(170, 140, 210, 31);

        listService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listServiceActionPerformed(evt);
            }
        });
        jPanel1.add(listService);
        listService.setBounds(170, 260, 210, 31);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
            Use_service.deleteUse_service(customer,customer.getList_service().get(listService.getSelectedIndex()).getId(),customer.getDate().get(listService.getSelectedIndex()));
            JOptionPane.showMessageDialog(rootPane, "Xoá dịch vụ thành công");
            ugui.showUse_service();
//        }
        this.setVisible(false);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtName_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName_roomActionPerformed

    private void listServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listService;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtName_customer;
    private javax.swing.JTextField txtName_room;
    // End of variables declaration//GEN-END:variables
}
