/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DTO.Service;
import BUS.Service_BUS;
import DTO.Staff;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vanhi
 */
public class EditService extends javax.swing.JFrame {
    ServiceGUI1 sgui = null;
    Service_BUS service_BUS = new Service_BUS();
    Service service = null;
    Staff staff = null;
    
    /**
     * Creates new form EditRoom
     */
    public EditService(Staff s) {
        initComponents();
        staff = s;
        sgui = new ServiceGUI1(s);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void infor(Service s,ServiceGUI1 SG){
        sgui = SG;
        service = s;
        if(s!=null){
            title.setText("Sửa thông tin dịch vụ");
            txtName.setText(s.getName());
            txtDescription.setText(s.getDescription());
            txtPrice.setText(String.valueOf(s.getPrice()));
            
        }else{
            title.setText("Thêm thông tin dịch vụ");
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(409, 434));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Chỉnh sửa dịch vụ");
        jPanel1.add(title);
        title.setBounds(0, 50, 410, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên dịch vụ :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 90, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Giá dịch vụ :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 240, 90, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mô tả :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 190, 90, 31);
        jPanel1.add(txtDescription);
        txtDescription.setBounds(120, 190, 250, 31);
        jPanel1.add(txtName);
        txtName.setBounds(120, 140, 250, 31);
        jPanel1.add(txtPrice);
        txtPrice.setBounds(120, 240, 250, 31);

        btnConfirm.setBackground(new java.awt.Color(52, 152, 219));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Xác nhận");
        btnConfirm.setBorderPainted(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm);
        btnConfirm.setBounds(30, 330, 340, 40);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String description = txtDescription.getText();
        String price = txtPrice.getText();
        if((name.length()==0)||(description.length()==0)||(price.length()==0)){
            JOptionPane.showMessageDialog(this, "Vui lòng không để trống thông tin");
        }else if(name.matches("^[0-9]+$")){
            JOptionPane.showMessageDialog(this, "Tên không hợp lệ");
        }
        else if(!price.matches("^[0-9]+$")){
            JOptionPane.showMessageDialog(this, "Giá không hợp lệ");
        }
        else{
            if(service!=null){
                service_BUS.editService(service,txtName.getText(),txtDescription.getText(), Integer.parseInt(txtPrice.getText()));
                JOptionPane.showMessageDialog(rootPane, "Chỉnh sửa thông tin dịch vụ thành công");
            }else{
                Service s = new Service(txtName.getText(),txtDescription.getText(), Integer.parseInt(txtPrice.getText()));
                service_BUS.addService(s);
                JOptionPane.showMessageDialog(rootPane, "Thêm thông tin dịch vụ thành công");
            }
            sgui.showService();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
