/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JPanel;
import DTO.Staff;

/**
 *
 * @author duykh
 */
public class MainGUI extends javax.swing.JFrame {

    Staff staff = new Staff();

    /**
     * Creates new form MainGUI
     */
    public MainGUI(Staff s) {
        initComponents();
        staff = s;
        Name.setText(staff.getName());
        Manager.setText(staff.isManager() ? "Manager" : "Staff");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        staffPage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        roomBtn = new javax.swing.JPanel();
        RoomBtn = new javax.swing.JLabel();
        staffBtn = new javax.swing.JPanel();
        StaffBtn = new javax.swing.JLabel();
        adminBtn = new javax.swing.JPanel();
        AdminBtn = new javax.swing.JLabel();
        hotelBtn = new javax.swing.JPanel();
        HotelBtn = new javax.swing.JLabel();
        totalBtn = new javax.swing.JPanel();
        TotalBtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Manager = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        roomNav = new javax.swing.JPanel();
        roomInfo = new javax.swing.JPanel();
        RoomLink = new javax.swing.JLabel();
        roomBookInfo = new javax.swing.JPanel();
        RoomLink2 = new javax.swing.JLabel();
        StaffNav = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        StaffLink = new javax.swing.JLabel();
        ServiceNav = new javax.swing.JPanel();
        serviceInfo = new javax.swing.JPanel();
        serviceInforLink = new javax.swing.JLabel();
        serviceUsing = new javax.swing.JPanel();
        serviceUsingLink = new javax.swing.JLabel();
        HotelNav = new javax.swing.JPanel();
        BillInfo = new javax.swing.JPanel();
        BillInfoLink = new javax.swing.JLabel();
        totalNav = new javax.swing.JPanel();
        accountInfo = new javax.swing.JPanel();
        accountInfoLink = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel8.setBackground(new java.awt.Color(30, 38, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(30, 38, 50));

        jPanel13.setBackground(new java.awt.Color(30, 38, 50));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 156, 175)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phùng Duy Khang");

        jLabel8.setForeground(new java.awt.Color(145, 156, 175));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manager");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(640, Short.MAX_VALUE))
        );

        staffPage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("staff page");

        javax.swing.GroupLayout staffPageLayout = new javax.swing.GroupLayout(staffPage);
        staffPage.setLayout(staffPageLayout);
        staffPageLayout.setHorizontalGroup(
            staffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPageLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel6)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        staffPageLayout.setVerticalGroup(
            staffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPageLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel6)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 106, 237));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Logo");

        jPanel11.setBackground(new java.awt.Color(55, 106, 237));

        roomBtn.setBackground(new java.awt.Color(55, 106, 237));

        RoomBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RoomBtn.setForeground(new java.awt.Color(255, 255, 255));
        RoomBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomBtn.setText("Room");
        RoomBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roomBtnLayout = new javax.swing.GroupLayout(roomBtn);
        roomBtn.setLayout(roomBtnLayout);
        roomBtnLayout.setHorizontalGroup(
            roomBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomBtnLayout.setVerticalGroup(
            roomBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        staffBtn.setBackground(new java.awt.Color(55, 106, 237));

        StaffBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        StaffBtn.setForeground(new java.awt.Color(255, 255, 255));
        StaffBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffBtn.setText("Staff");
        StaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout staffBtnLayout = new javax.swing.GroupLayout(staffBtn);
        staffBtn.setLayout(staffBtnLayout);
        staffBtnLayout.setHorizontalGroup(
            staffBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        staffBtnLayout.setVerticalGroup(
            staffBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        adminBtn.setBackground(new java.awt.Color(55, 106, 237));

        AdminBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminBtn.setText("Service");
        AdminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout adminBtnLayout = new javax.swing.GroupLayout(adminBtn);
        adminBtn.setLayout(adminBtnLayout);
        adminBtnLayout.setHorizontalGroup(
            adminBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminBtnLayout.setVerticalGroup(
            adminBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        hotelBtn.setBackground(new java.awt.Color(55, 106, 237));

        HotelBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HotelBtn.setForeground(new java.awt.Color(255, 255, 255));
        HotelBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HotelBtn.setText("Bill");
        HotelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hotelBtnLayout = new javax.swing.GroupLayout(hotelBtn);
        hotelBtn.setLayout(hotelBtnLayout);
        hotelBtnLayout.setHorizontalGroup(
            hotelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hotelBtnLayout.setVerticalGroup(
            hotelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HotelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        totalBtn.setBackground(new java.awt.Color(55, 106, 237));

        TotalBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalBtn.setForeground(new java.awt.Color(255, 255, 255));
        TotalBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalBtn.setText("Account");
        TotalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout totalBtnLayout = new javax.swing.GroupLayout(totalBtn);
        totalBtn.setLayout(totalBtnLayout);
        totalBtnLayout.setHorizontalGroup(
            totalBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TotalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        totalBtnLayout.setVerticalGroup(
            totalBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staffBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(roomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hotelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(totalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(699, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(30, 38, 50));

        jPanel6.setBackground(new java.awt.Color(30, 38, 50));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 156, 175)));

        Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Khang cu siêu bé");

        Manager.setForeground(new java.awt.Color(145, 156, 175));
        Manager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manager.setText("Manager");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Manager)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        roomNav.setBackground(new java.awt.Color(30, 38, 50));

        roomInfo.setBackground(new java.awt.Color(30, 38, 50));

        RoomLink.setBackground(new java.awt.Color(145, 156, 175));
        RoomLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RoomLink.setForeground(new java.awt.Color(145, 156, 175));
        RoomLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomLink.setText("Thông tin phòng");
        RoomLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roomInfoLayout = new javax.swing.GroupLayout(roomInfo);
        roomInfo.setLayout(roomInfoLayout);
        roomInfoLayout.setHorizontalGroup(
            roomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        roomInfoLayout.setVerticalGroup(
            roomInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        roomBookInfo.setBackground(new java.awt.Color(30, 38, 50));

        RoomLink2.setBackground(new java.awt.Color(145, 156, 175));
        RoomLink2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RoomLink2.setForeground(new java.awt.Color(145, 156, 175));
        RoomLink2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomLink2.setText("Thông tin đặt phòng");
        RoomLink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomLink2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roomBookInfoLayout = new javax.swing.GroupLayout(roomBookInfo);
        roomBookInfo.setLayout(roomBookInfoLayout);
        roomBookInfoLayout.setHorizontalGroup(
            roomBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomLink2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomBookInfoLayout.setVerticalGroup(
            roomBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomLink2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roomNavLayout = new javax.swing.GroupLayout(roomNav);
        roomNav.setLayout(roomNavLayout);
        roomNavLayout.setHorizontalGroup(
            roomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roomBookInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomNavLayout.setVerticalGroup(
            roomNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomNavLayout.createSequentialGroup()
                .addComponent(roomInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(roomBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 573, Short.MAX_VALUE))
        );

        StaffNav.setBackground(new java.awt.Color(30, 38, 50));

        jPanel15.setBackground(new java.awt.Color(30, 38, 50));

        StaffLink.setBackground(new java.awt.Color(145, 156, 175));
        StaffLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        StaffLink.setForeground(new java.awt.Color(145, 156, 175));
        StaffLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffLink.setText("Danh sách nhân viên");
        StaffLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout StaffNavLayout = new javax.swing.GroupLayout(StaffNav);
        StaffNav.setLayout(StaffNavLayout);
        StaffNavLayout.setHorizontalGroup(
            StaffNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StaffNavLayout.setVerticalGroup(
            StaffNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffNavLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ServiceNav.setBackground(new java.awt.Color(30, 38, 50));

        serviceInfo.setBackground(new java.awt.Color(30, 38, 50));

        serviceInforLink.setBackground(new java.awt.Color(145, 156, 175));
        serviceInforLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        serviceInforLink.setForeground(new java.awt.Color(145, 156, 175));
        serviceInforLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceInforLink.setText("Thông tin dịch vụ");
        serviceInforLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceInforLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout serviceInfoLayout = new javax.swing.GroupLayout(serviceInfo);
        serviceInfo.setLayout(serviceInfoLayout);
        serviceInfoLayout.setHorizontalGroup(
            serviceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceInforLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        serviceInfoLayout.setVerticalGroup(
            serviceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceInforLink, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        serviceUsing.setBackground(new java.awt.Color(30, 38, 50));

        serviceUsingLink.setBackground(new java.awt.Color(145, 156, 175));
        serviceUsingLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        serviceUsingLink.setForeground(new java.awt.Color(145, 156, 175));
        serviceUsingLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceUsingLink.setText("Phiếu sử dụng dịch vụ");
        serviceUsingLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceUsingLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout serviceUsingLayout = new javax.swing.GroupLayout(serviceUsing);
        serviceUsing.setLayout(serviceUsingLayout);
        serviceUsingLayout.setHorizontalGroup(
            serviceUsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceUsingLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        serviceUsingLayout.setVerticalGroup(
            serviceUsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceUsingLink, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout ServiceNavLayout = new javax.swing.GroupLayout(ServiceNav);
        ServiceNav.setLayout(ServiceNavLayout);
        ServiceNavLayout.setHorizontalGroup(
            ServiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serviceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(serviceUsing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ServiceNavLayout.setVerticalGroup(
            ServiceNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceNavLayout.createSequentialGroup()
                .addComponent(serviceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(serviceUsing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
        );

        HotelNav.setBackground(new java.awt.Color(30, 38, 50));

        BillInfo.setBackground(new java.awt.Color(30, 38, 50));

        BillInfoLink.setBackground(new java.awt.Color(145, 156, 175));
        BillInfoLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BillInfoLink.setForeground(new java.awt.Color(145, 156, 175));
        BillInfoLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BillInfoLink.setText("Thông tin các hoá đơn");
        BillInfoLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillInfoLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BillInfoLayout = new javax.swing.GroupLayout(BillInfo);
        BillInfo.setLayout(BillInfoLayout);
        BillInfoLayout.setHorizontalGroup(
            BillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillInfoLink, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        BillInfoLayout.setVerticalGroup(
            BillInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillInfoLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HotelNavLayout = new javax.swing.GroupLayout(HotelNav);
        HotelNav.setLayout(HotelNavLayout);
        HotelNavLayout.setHorizontalGroup(
            HotelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HotelNavLayout.setVerticalGroup(
            HotelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelNavLayout.createSequentialGroup()
                .addComponent(BillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(609, Short.MAX_VALUE))
        );

        totalNav.setBackground(new java.awt.Color(30, 38, 50));

        accountInfo.setBackground(new java.awt.Color(30, 38, 50));

        accountInfoLink.setBackground(new java.awt.Color(145, 156, 175));
        accountInfoLink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        accountInfoLink.setForeground(new java.awt.Color(145, 156, 175));
        accountInfoLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountInfoLink.setText("Thông tin tài khoản");
        accountInfoLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountInfoLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountInfoLayout = new javax.swing.GroupLayout(accountInfo);
        accountInfo.setLayout(accountInfoLayout);
        accountInfoLayout.setHorizontalGroup(
            accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountInfoLink, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        accountInfoLayout.setVerticalGroup(
            accountInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountInfoLink, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout totalNavLayout = new javax.swing.GroupLayout(totalNav);
        totalNav.setLayout(totalNavLayout);
        totalNavLayout.setHorizontalGroup(
            totalNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        totalNavLayout.setVerticalGroup(
            totalNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalNavLayout.createSequentialGroup()
                .addComponent(accountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(984, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(roomNav, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(StaffNav, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ServiceNav, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(HotelNav, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalNav, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ServiceNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(HotelNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(totalNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StaffNav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomNav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(ServiceNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(HotelNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(totalNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chào mừng Tên");
        jLabel3.setPreferredSize(new java.awt.Dimension(22, 22));
        jPanel3.add(jLabel3);

        jPanel2.add(jPanel3, "card2");

        jLayeredPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1700, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setVisibleSemiNav(JPanel semiNav) {
        StaffNav.setVisible(false);
        roomNav.setVisible(false);
        ServiceNav.setVisible(false);
        totalNav.setVisible(false);
        HotelNav.setVisible(false);
        semiNav.setVisible(true);
    }

    public void setColorChoose(JPanel navBtn) {
        roomBtn.setBackground(new java.awt.Color(55, 106, 237));
        staffBtn.setBackground(new java.awt.Color(55, 106, 237));
        adminBtn.setBackground(new java.awt.Color(55, 106, 237));
        totalBtn.setBackground(new java.awt.Color(55, 106, 237));
        hotelBtn.setBackground(new java.awt.Color(55, 106, 237));
        navBtn.setBackground(new java.awt.Color(30, 38, 50));
    }

    public void setColorNavChoose(JPanel semiNavBtn) {
        roomInfo.setBackground(new java.awt.Color(30, 38, 50));
        roomBookInfo.setBackground(new java.awt.Color(30, 38, 50));
        jPanel15.setBackground(new java.awt.Color(30, 38, 50));
        serviceInfo.setBackground(new java.awt.Color(30, 38, 50));
        serviceUsing.setBackground(new java.awt.Color(30, 38, 50));
        BillInfo.setBackground(new java.awt.Color(30, 38, 50));
        accountInfo.setBackground(new java.awt.Color(30, 38, 50));
        semiNavBtn.setBackground(new java.awt.Color(255, 255, 255));
    }

    public void switchPanel(JPanel target, JPanel page) {
        target.removeAll();
        target.invalidate();
        target.add(page);
        target.revalidate();
    }


    private void RoomBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomBtnMouseClicked
        // TODO add your handling code here:
        setVisibleSemiNav(roomNav);
        setColorChoose(roomBtn);
    }//GEN-LAST:event_RoomBtnMouseClicked

    private void StaffBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffBtnMouseClicked
        // TODO add your handling code here:
        setVisibleSemiNav(StaffNav);
        setColorChoose(staffBtn);
    }//GEN-LAST:event_StaffBtnMouseClicked

    private void RoomLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new RoomGUI(staff));
        setColorNavChoose(roomInfo);
    }//GEN-LAST:event_RoomLinkMouseClicked

    private void AdminBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBtnMouseClicked
        // TODO add your handling code here:
        setVisibleSemiNav(ServiceNav);
        setColorChoose(adminBtn);
    }//GEN-LAST:event_AdminBtnMouseClicked

    private void HotelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelBtnMouseClicked
        // TODO add your handling code here:
        setVisibleSemiNav(HotelNav);
        setColorChoose(hotelBtn);

    }//GEN-LAST:event_HotelBtnMouseClicked

    private void TotalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalBtnMouseClicked
        // TODO add your handling code here:
        setVisibleSemiNav(totalNav);
        setColorChoose(totalBtn);
    }//GEN-LAST:event_TotalBtnMouseClicked

    private void StaffLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new StaffGUI(staff));
        setColorNavChoose(jPanel15);
    }//GEN-LAST:event_StaffLinkMouseClicked

    private void RoomLink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomLink2MouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new BookingGUI(staff));
        setColorNavChoose(roomBookInfo);
    }//GEN-LAST:event_RoomLink2MouseClicked

    private void serviceUsingLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceUsingLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new Use_serviceGUI());
        setColorNavChoose(serviceUsing);
    }//GEN-LAST:event_serviceUsingLinkMouseClicked

    private void serviceInforLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceInforLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new ServiceGUI1(staff));
        setColorNavChoose(serviceInfo);
    }//GEN-LAST:event_serviceInforLinkMouseClicked

    private void BillInfoLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillInfoLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new BillGUI());
        setColorNavChoose(BillInfo);
    }//GEN-LAST:event_BillInfoLinkMouseClicked

    private void accountInfoLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountInfoLinkMouseClicked
        // TODO add your handling code here:
        switchPanel(jPanel2, new AccountGUI1111(staff));
        setColorNavChoose(accountInfo);
    }//GEN-LAST:event_accountInfoLinkMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.out.println("GUI.MainGUI.jLabel1MouseClicked()");
    }// GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                this.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminBtn;
    private javax.swing.JPanel BillInfo;
    private javax.swing.JLabel BillInfoLink;
    private javax.swing.JLabel HotelBtn;
    private javax.swing.JPanel HotelNav;
    private javax.swing.JLabel Manager;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel RoomBtn;
    private javax.swing.JLabel RoomLink;
    private javax.swing.JLabel RoomLink2;
    private javax.swing.JPanel ServiceNav;
    private javax.swing.JLabel StaffBtn;
    private javax.swing.JLabel StaffLink;
    private javax.swing.JPanel StaffNav;
    private javax.swing.JLabel TotalBtn;
    private javax.swing.JPanel accountInfo;
    private javax.swing.JLabel accountInfoLink;
    private javax.swing.JPanel adminBtn;
    private javax.swing.JPanel hotelBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel roomBookInfo;
    private javax.swing.JPanel roomBtn;
    private javax.swing.JPanel roomInfo;
    private javax.swing.JPanel roomNav;
    private javax.swing.JPanel serviceInfo;
    private javax.swing.JLabel serviceInforLink;
    private javax.swing.JPanel serviceUsing;
    private javax.swing.JLabel serviceUsingLink;
    private javax.swing.JPanel staffBtn;
    private javax.swing.JPanel staffPage;
    private javax.swing.JPanel totalBtn;
    private javax.swing.JPanel totalNav;
    // End of variables declaration//GEN-END:variables
}
