/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Bill;
import DTO.Room;
import DTO.Service;
import DTO.Use_service;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author vanhi
 */
public class ThongkeGUI extends javax.swing.JPanel {
    DefaultTableModel model;
    /**
     * Creates new form StatisticalGUI
     */
    public ThongkeGUI() {
        initComponents();
        showThongke();
    }
    public void showThongke() {
        String type = String.valueOf(type_choose.getSelectedItem());
        ArrayList<Bill> list_bill = Bill.SelectAll();
        model = (DefaultTableModel) tb_thongke.getModel();
        int i=1;
        int total = 0;
        switch (type){
            case "Room":
                ArrayList<Room> list_room = Room.SelectAll();
                model.setColumnIdentifiers(new Object[]{
                "STT", "Tên phòng", "Giá tiền", "Số lần được đặt", "Tổng tiền thu được"
                });
                model.setRowCount(0);
                for (Room r : list_room) {
                    int count = 0;
                    for (Bill b : list_bill) {
                        if(b.getBooking().getRoom().getId() == r.getId() && b.getBooking().getTimestamp().getMonth() == month_choose.getSelectedIndex() && (b.getBooking().getTimestamp().getYear()+1900) == year_choose.getYear()){
                            count ++;
                        }
                    }
                    model.addRow(new Object[]{
                        i++, r.getName(), r.getPrice()+".000đ", count, count==0?0:count*r.getPrice()+".000đ"
                    });
                    total += count*r.getPrice();
                }
                break;
            case "Service":
                ArrayList<Service> list_service = Service.SelectAll();
                ArrayList<Use_service> list_use_service = Use_service.SelectAll_withoutGroupBy();
                model.setColumnIdentifiers(new Object[]{
                "STT", "Tên dịch vụ", "Giá tiền", "Số lần được đặt", "Tổng tiền thu được"
                });
                model.setRowCount(0);
                for (Service s : list_service) {
                    int count = 0;
                    for (Use_service us : list_use_service) {
                        if(us.getService().getId() == s.getId() && us.getTimestamp().getMonth() == month_choose.getSelectedIndex() && (us.getTimestamp().getYear()+1900) == year_choose.getYear()){
                            count ++;
                        }
                    }
                    model.addRow(new Object[]{
                        i++, s.getName(), s.getPrice()+".000đ", count, count==0?0:count*s.getPrice()+".000đ"
                    });
                    total += count*s.getPrice();
                }
                break;
        }
        model.addRow(new Object[]{
            "", "", "", "Tổng cộng :",total==0?total : total+".000đ"
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_thongke = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        type_choose = new javax.swing.JComboBox<>();
        month_choose = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        year_choose = new com.toedter.calendar.JYearChooser();
        btn_output = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tb_thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_thongke);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống kê");

        type_choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room", "Service" }));
        type_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_chooseActionPerformed(evt);
            }
        });

        month_choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "Septemper", "Octorber", "November", "December", " " }));
        month_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_chooseActionPerformed(evt);
            }
        });

        jLabel2.setText("Month :");

        jLabel3.setText("Type :");

        jLabel4.setText("Year :");

        year_choose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                year_choosePropertyChange(evt);
            }
        });

        btn_output.setBackground(new java.awt.Color(51, 153, 255));
        btn_output.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_output.setForeground(new java.awt.Color(255, 255, 255));
        btn_output.setText("Xuất thông tin");
        btn_output.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_output, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_output, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void month_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_chooseActionPerformed
        // TODO add your handling code here:
        showThongke();
    }//GEN-LAST:event_month_chooseActionPerformed

    private void type_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_chooseActionPerformed
        // TODO add your handling code here:
        showThongke();
    }//GEN-LAST:event_type_chooseActionPerformed

    private void year_choosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_year_choosePropertyChange
        // TODO add your handling code here:
        showThongke();
    }//GEN-LAST:event_year_choosePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month_choose;
    private javax.swing.JTable tb_thongke;
    private javax.swing.JComboBox<String> type_choose;
    private com.toedter.calendar.JYearChooser year_choose;
    // End of variables declaration//GEN-END:variables
}
